import jsPDF from 'jspdf';
import 'jspdf-autotable';

// Document Service - Handles PDF generation for payment documents
// This service creates professional PDF documents for payment schedules, bank instructions, and memos

/**
 * Generate a payment schedule PDF document
 * @param {Object} scheduleData - Payment schedule data
 * @param {string} sheetName - Name of the weekly sheet
 * @param {Object} options - Document options
 * @returns {jsPDF} Generated PDF document
 */
export const generatePaymentSchedulePDF = (scheduleData, sheetName, options = {}) => {
  const doc = new jsPDF();
  
  // Document header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('PAYMENT SCHEDULE', 105, 20, { align: 'center' });
  
  // Sheet information
  doc.setFontSize(14);
  doc.setFont('helvetica', 'normal');
  doc.text(`Weekly Sheet: ${sheetName}`, 20, 35);
  doc.text(`Generated: ${new Date().toLocaleDateString()}`, 20, 45);
  doc.text(`Total Payments: ${scheduleData.payments?.length || 0}`, 20, 55);
  
  // Payment details table
  if (scheduleData.payments && scheduleData.payments.length > 0) {
    const tableData = scheduleData.payments.map(payment => [
      payment.date || '',
      payment.vendor || payment.vendors || '',
      payment.description || payment.descriptions || '',
      payment.amount || payment.fullPretax || '0',
      payment.currency || 'GHS',
      payment.paymentMode || '',
      payment.bank || ''
    ]);
    
    doc.autoTable({
      startY: 70,
      head: [['Date', 'Vendor', 'Description', 'Amount', 'Currency', 'Payment Mode', 'Bank']],
      body: tableData,
      theme: 'grid',
      headStyles: {
        fillColor: [66, 139, 202],
        textColor: 255,
        fontSize: 10
      },
      styles: {
        fontSize: 9,
        cellPadding: 3
      },
      columnStyles: {
        0: { cellWidth: 25 }, // Date
        1: { cellWidth: 40 }, // Vendor
        2: { cellWidth: 50 }, // Description
        3: { cellWidth: 25, halign: 'right' }, // Amount
        4: { cellWidth: 20 }, // Currency
        5: { cellWidth: 30 }, // Payment Mode
        6: { cellWidth: 30 }  // Bank
      }
    });
  }
  
  // Summary section
  const finalY = doc.lastAutoTable.finalY || 70;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Summary', 20, finalY + 20);
  
  // Calculate totals
  const totalAmount = scheduleData.payments?.reduce((sum, p) => sum + (parseFloat(p.amount || p.fullPretax || 0)), 0) || 0;
  const totalPayments = scheduleData.payments?.length || 0;
  
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Amount: ${totalAmount.toFixed(2)}`, 20, finalY + 30);
  doc.text(`Number of Payments: ${totalPayments}`, 20, finalY + 40);
  
  // Footer
  doc.setFontSize(10);
  doc.text('Generated by Payment Schedule System', 105, doc.internal.pageSize.height - 10, { align: 'center' });
  
  return doc;
};

/**
 * Generate a bank instruction PDF document
 * @param {Object} bankData - Bank instruction data
 * @param {string} sheetName - Name of the weekly sheet
 * @param {Object} options - Document options
 * @returns {jsPDF} Generated PDF document
 */
export const generateBankInstructionPDF = (bankData, sheetName, options = {}) => {
  const doc = new jsPDF();
  
  // Document header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('BANK INSTRUCTION', 105, 20, { align: 'center' });
  
  // Bank details
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Bank Details:', 20, 40);
  
  doc.setFont('helvetica', 'normal');
  doc.text(`Bank: ${bankData.bank || 'Not specified'}`, 20, 55);
  doc.text(`Account: ${bankData.accountNumber || 'Not specified'}`, 20, 65);
  doc.text(`Sheet: ${sheetName}`, 20, 75);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 85);
  
  // Payment instructions table
  if (bankData.payments && bankData.payments.length > 0) {
    const tableData = bankData.payments.map(payment => [
      payment.vendor || payment.vendors || '',
      payment.amount || payment.fullPretax || '0',
      payment.currency || 'GHS',
      payment.bank || '',
      payment.paymentMode || ''
    ]);
    
    doc.autoTable({
      startY: 100,
      head: [['Vendor', 'Amount', 'Currency', 'Bank', 'Payment Mode']],
      body: tableData,
      theme: 'grid',
      headStyles: {
        fillColor: [66, 139, 202],
        textColor: 255,
        fontSize: 10
      },
      styles: {
        fontSize: 9,
        cellPadding: 3
      },
      columnStyles: {
        0: { cellWidth: 50 }, // Vendor
        1: { cellWidth: 30, halign: 'right' }, // Amount
        2: { cellWidth: 25 }, // Currency
        3: { cellWidth: 35 }, // Bank
        4: { cellWidth: 30 }  // Payment Mode
      }
    });
  }
  
  // Instructions
  const finalY = doc.lastAutoTable.finalY || 100;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('Instructions:', 20, finalY + 20);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('1. Process all payments listed above', 20, finalY + 30);
  doc.text('2. Ensure sufficient funds are available', 20, finalY + 40);
  doc.text('3. Confirm all transfers are completed', 20, finalY + 50);
  doc.text('4. Report any issues immediately', 20, finalY + 60);
  
  // Footer
  doc.setFontSize(10);
  doc.text('Generated by Payment Schedule System', 105, doc.internal.pageSize.height - 10, { align: 'center' });
  
  return doc;
};

/**
 * Generate a payment memo PDF document
 * @param {Object} memoData - Memo data
 * @param {string} sheetName - Name of the weekly sheet
 * @param {Object} options - Document options
 * @returns {jsPDF} Generated PDF document
 */
export const generatePaymentMemoPDF = (memoData, sheetName, options = {}) => {
  const doc = new jsPDF();
  
  // Document header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('PAYMENT MEMO', 105, 20, { align: 'center' });
  
  // Memo details
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Memo Details:', 20, 40);
  
  doc.setFont('helvetica', 'normal');
  doc.text(`Subject: Payment Schedule for ${sheetName}`, 20, 55);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 65);
  doc.text(`Prepared By: ${memoData.preparedBy || 'System User'}`, 20, 75);
  doc.text(`Department: ${memoData.department || 'Finance'}`, 20, 85);
  
  // Purpose section
  doc.setFont('helvetica', 'bold');
  doc.text('Purpose:', 20, 105);
  
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text('This memo requests approval for the payment schedule attached.', 20, 115);
  doc.text('The schedule contains payments for various vendors and services', 20, 125);
  doc.text('as approved in the weekly budget allocation.', 20, 135);
  
  // Summary
  doc.setFont('helvetica', 'bold');
  doc.text('Summary:', 20, 155);
  
  const totalAmount = memoData.payments?.reduce((sum, p) => sum + (parseFloat(p.amount || p.fullPretax || 0)), 0) || 0;
  const totalPayments = memoData.payments?.length || 0;
  
  doc.setFont('helvetica', 'normal');
  doc.text(`Total Amount: ${totalAmount.toFixed(2)}`, 20, 165);
  doc.text(`Number of Payments: ${totalPayments}`, 20, 175);
  doc.text(`Currency: ${memoData.currency || 'GHS'}`, 20, 185);
  
  // Approval section
  doc.setFont('helvetica', 'bold');
  doc.text('Approval:', 20, 205);
  
  doc.setFont('helvetica', 'normal');
  doc.text('Checked By: _________________ Date: ___________', 20, 215);
  doc.text('Approved By: _________________ Date: ___________', 20, 225);
  doc.text('Authorized By: _________________ Date: ___________', 20, 235);
  
  // Footer
  doc.setFontSize(10);
  doc.text('Generated by Payment Schedule System', 105, doc.internal.pageSize.height - 10, { align: 'center' });
  
  return doc;
};

/**
 * Generate a WHT return PDF document
 * @param {Object} whtData - WHT return data
 * @param {string} sheetName - Name of the weekly sheet
 * @param {Object} options - Document options
 * @returns {jsPDF} Generated PDF document
 */
export const generateWHTReturnPDF = (whtData, sheetName, options = {}) => {
  const doc = new jsPDF();
  
  // Document header
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('WHT RETURN', 105, 20, { align: 'center' });
  
  // WHT details
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text('Withholding Tax Return Details:', 20, 40);
  
  doc.setFont('helvetica', 'normal');
  doc.text(`Period: ${whtData.period || 'Weekly'}`, 20, 55);
  doc.text(`Sheet: ${sheetName}`, 20, 65);
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 75);
  
  // WHT breakdown table
  if (whtData.payments && whtData.payments.length > 0) {
    const tableData = whtData.payments.map(payment => [
      payment.vendor || payment.vendors || '',
      payment.amount || payment.fullPretax || '0',
      payment.procurementType || payment.procurement || '',
      payment.whtAmount || '0',
      payment.whtRate || '0%'
    ]);
    
    doc.autoTable({
      startY: 90,
      head: [['Vendor', 'Amount', 'Procurement Type', 'WHT Amount', 'WHT Rate']],
      body: tableData,
      theme: 'grid',
      headStyles: {
        fillColor: [66, 139, 202],
        textColor: 255,
        fontSize: 10
      },
      styles: {
        fontSize: 9,
        cellPadding: 3
      },
      columnStyles: {
        0: { cellWidth: 50 }, // Vendor
        1: { cellWidth: 30, halign: 'right' }, // Amount
        2: { cellWidth: 35 }, // Procurement Type
        3: { cellWidth: 30, halign: 'right' }, // WHT Amount
        4: { cellWidth: 25 }  // WHT Rate
      }
    });
  }
  
  // Summary
  const finalY = doc.lastAutoTable.finalY || 90;
  doc.setFontSize(12);
  doc.setFont('helvetica', 'bold');
  doc.text('WHT Summary:', 20, finalY + 20);
  
  const totalWHT = whtData.payments?.reduce((sum, p) => sum + (parseFloat(p.whtAmount || 0)), 0) || 0;
  const totalAmount = whtData.payments?.reduce((sum, p) => sum + (parseFloat(p.amount || p.fullPretax || 0)), 0) || 0;
  
  doc.setFont('helvetica', 'normal');
  doc.text(`Total WHT Amount: ${totalWHT.toFixed(2)}`, 20, finalY + 30);
  doc.text(`Total Payment Amount: ${totalAmount.toFixed(2)}`, 20, finalY + 40);
  doc.text(`WHT Percentage: ${((totalWHT / totalAmount) * 100).toFixed(2)}%`, 20, finalY + 50);
  
  // Footer
  doc.setFontSize(10);
  doc.text('Generated by Payment Schedule System', 105, doc.internal.pageSize.height - 10, { align: 'center' });
  
  return doc;
};

/**
 * Download a PDF document
 * @param {jsPDF} doc - Generated PDF document
 * @param {string} filename - Name of the file to download
 */
export const downloadPDF = (doc, filename) => {
  doc.save(filename);
};

/**
 * Open a PDF document in a new tab
 * @param {jsPDF} doc - Generated PDF document
 */
export const openPDF = (doc) => {
  const pdfDataUri = doc.output('datauristring');
  window.open(pdfDataUri, '_blank');
};
